# Generated by Django 5.0 on 2024-01-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_make', models.CharField(max_length=50)),
                ('car_brand', models.CharField(default='', max_length=50)),
                ('car_type', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/images')),
            ],
        ),
    ]
